name: Compile Ping Monitor X Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PingMonitor Source Code
      uses: actions/checkout@v4

    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle Global Environment
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2' # Installs a full, certified Gradle installation directly onto the runner

    - name: Generate Debug Keystore
      run: |
        mkdir -p ~/.android
        keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: Assemble Debug APK Binary
      run: gradle assembleDebug --stacktrace
